### PR TITLE
xz compression and .lzma extension

### LINKED ISSUE #79: Support for xz compression
Hi, it would be great to support xz file compression as well. Thanks for your great software btw.

### PR DESCRIPTION
**Pull request by cypriani**
This fixes #79 and #84.

For #79, I did not:
- update the line numbers in the po files (not sure it's necessary, and they were wrong already)
- add a "supported since version" note in user-guide.sgml

### CODE REVIEW

**Comment by kissifrot** [comment]
Can you change the PR to target _devel_ branch?

**Comment by cypriani** [comment]
> Le 19 nov. 2016 à 17:29, Philippe Villiers <notifications@github.com> a écrit :
> Can you change the PR to target devel branch?
> 

Sorry, I didn't see that there was a devel branch. I should have time to update the PR on Monday.

**Comment by cypriani** [comment]
Done, but the update has included a merge commit. Would you rather have me create a new PR from my own devel branch?

**Comment by kissifrot** [comment]
Yes it would be better

**Pull request closed without merging**
